### ISSUE TITLE
응원글 수정 이슈

### ISSUE THREAD

**Issue by hyunssooo** [devham76/springboot2-webservice#1]
응원글에 글 등록은 되지 않지만 이미 존재하는 글은 수정이 가능하네요 :) 

우연히 들어왔는데 잘 보고 갑니다! 파이팅

응원글 첫번째 글에 g라고 붙여 놨습니다~!

**Comment by devham76** [comment]
등록과 수정은 인증된 사용자만 가능하도록 했는데 
수정 되는부분은 코드를 수정해야겠네요 !

**Comment by devham76** [comment]
응원 감사합니다 ! :)
